# Run Vibe.d's test suite on all three platforms
name: CI

on: [push, pull_request]

jobs:
  main:
    name: Run
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        dc:
          - dmd-latest
          - dmd-2.096.1
          - dmd-2.095.1
          - dmd-2.092.1
          - dmd-2.087.1
          - ldc-latest
          - ldc-1.26.0
          - ldc-1.25.0
          - ldc-1.22.0
          - ldc-1.17.0
        include:
          # Default
          - { parts: 'builds,unittests,examples,tests,mongo' }
          # Custom part for coverage
          - { dc: dmd-latest, parts: 'unittests,tests,coverage'}
          - { os: ubuntu-latest, dc: ldc-latest, parts: 'unittests,examples,tests,vibe-http' }

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    services:
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/creating-redis-service-containers
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare compiler
      uses: dlang-community/setup-dlang@v1
      with:
          compiler: ${{ matrix.dc }}

    - name: '[POSIX] Run tests'
      env:
        VIBED_DRIVER: vibe-core
        PARTS: ${{matrix.parts}}
      run: |
        git fetch --tags
        ./travis-ci.sh

    - name: '[DMD] Upload coverage to Codecov'
      if: matrix.parts == 'unittests,tests'
      uses: codecov/codecov-action@v1
